/**
 * Report generation — Markdown and JSON output.
 * Used by /report command and automatically by the engine.
 */

import * as fs from 'fs';
import * as path from 'path';

export interface ReportData {
  title: string;
  date: string;
  provider?: string;
  model?: string;
  findings: ReportFinding[];
  summary: {
    totalFindings: number;
    severities: Record<string, number>;
    verdict: string;
  };
  conversation?: { role: string; content: string }[];
}

export interface ReportFinding {
  type: string;
  severity: string;
  description: string;
  evidence: string;
  context?: string;
  remediation?: string;
}

// ─── Markdown Report ──────────────────────────────────────────

export function generateMarkdown(data: ReportData): string {
  const lines: string[] = [];

  lines.push(`# [ Sentinel Oracle ] — ${data.title}`);
  lines.push('');
  lines.push(`**Date:** ${data.date}`);
  if (data.provider) lines.push(`**Provider:** ${data.provider} ${data.model ? `(${data.model})` : ''}`);
  lines.push('');

  // Summary
  lines.push('## Summary');
  lines.push('');
  lines.push(`- **Verdict:** ${data.summary.verdict}`);
  lines.push(`- **Total Findings:** ${data.summary.totalFindings}`);
  for (const [sev, count] of Object.entries(data.summary.severities)) {
    if (count > 0) lines.push(`- **${sev}:** ${count}`);
  }
  lines.push('');

  // Findings
  lines.push('## Findings');
  lines.push('');

  if (data.findings.length === 0) {
    lines.push('_No findings to report._');
  } else {
    // Group by severity
    const order = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW'];
    for (const sev of order) {
      const sevFindings = data.findings.filter(f => f.severity.toUpperCase() === sev);
      if (sevFindings.length === 0) continue;

      lines.push(`### ${sev} (${sevFindings.length})`);
      lines.push('');

      for (const f of sevFindings) {
        lines.push(`#### ${f.type}`);
        lines.push('');
        if (f.context) lines.push(`- **Context:** ${f.context}`);
        lines.push(`- **Description:** ${f.description}`);
        if (f.evidence) lines.push(`- **Evidence:** \`${f.evidence}\``);
        if (f.remediation) lines.push(`- **Remediation:** ${f.remediation}`);
        lines.push('');
      }
    }
  }

  // Conversation log
  if (data.conversation && data.conversation.length > 0) {
    lines.push('## Conversation Log');
    lines.push('');
    lines.push('```');
    for (const msg of data.conversation) {
      const prefix = msg.role === 'user' ? '> ' : msg.role === 'assistant' ? '  ' : '  [tool] ';
      lines.push(prefix + msg.content.substring(0, 500));
    }
    lines.push('```');
  }

  lines.push('---');
  lines.push('_Generated by Sentinel Oracle Core_');

  return lines.join('\n');
}

// ─── JSON Report ──────────────────────────────────────────────

export function generateJSON(data: ReportData): string {
  return JSON.stringify(data, null, 2);
}

// ─── Save report to file ─────────────────────────────────────

export function saveReport(content: string, filename: string): string {
  const reportDir = path.join(process.env.HOME || process.env.USERPROFILE || '.', '.sentinel', 'reports');
  if (!fs.existsSync(reportDir)) fs.mkdirSync(reportDir, { recursive: true });

  const filePath = path.join(reportDir, filename);
  fs.writeFileSync(filePath, content, 'utf-8');
  return filePath;
}

// ─── Extract findings from scan output ───────────────────────

export function parseFindingsFromOutput(output: string, type: string): ReportFinding[] {
  const findings: ReportFinding[] = [];
  const lines = output.split('\n');

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    // Match patterns like: "CRITICAL — SECRET_AWS_KEY_ID in file:line"
    const criticalMatch = line.match(/(CRITICAL|HIGH|MEDIUM|LOW)\].*?(\w+)\s+in\s+(\S+?):(\d+)/i);
    if (criticalMatch) {
      const sev = criticalMatch[1].toUpperCase();
      const findingType = criticalMatch[2];
      const location = `${criticalMatch[3]}:${criticalMatch[4]}`;
      const evidence = lines[i + 1]?.trim() || '';
      findings.push({
        type: findingType,
        severity: sev,
        description: line.trim(),
        evidence: evidence,
        context: location,
        remediation: getDefaultRemediation(findingType),
      });
      continue;
    }

    // Match pattern: "■ [SEVERITY] TYPE in file:line"
    const bracketMatch = line.match(/■\s+\[(\w+)\]\s+(\w+)\s+in\s+(\S+):(\d+)/);
    if (bracketMatch) {
      findings.push({
        type: bracketMatch[2],
        severity: bracketMatch[1],
        description: line.trim(),
        evidence: lines[i + 1]?.trim() || '',
        context: `${bracketMatch[3]}:${bracketMatch[4]}`,
        remediation: getDefaultRemediation(bracketMatch[2]),
      });
    }
  }

  return findings;
}

function getDefaultRemediation(type: string): string {
  const remediations: Record<string, string> = {
    SECRET_AWS_KEY_ID: 'Rotate the key in AWS IAM, remove from code, use AWS Secrets Manager or environment variables',
    SECRET_AWS_SECRET: 'Rotate the secret in AWS IAM, remove from code, use AWS Secrets Manager',
    SECRET_GITHUB_TOKEN: 'Revoke the token in GitHub Settings > Developer settings > Personal access tokens',
    SECRET_STRIPE_KEY: 'Rotate the key in Stripe Dashboard > Developers > API keys, use Stripe CLI for local development',
    SECRET_SLACK_TOKEN: 'Revoke the token at api.slack.com > Apps > Your App > OAuth & Permissions',
    SECRET_SLACK_WEBHOOK: 'Delete the webhook at api.slack.com > Apps > Your App > Incoming Webhooks',
    SECRET_SSH_KEY: 'Generate a new SSH key pair, update authorized_keys, revoke the old key',
    SECRET_JWT: 'Rotate the JWT secret, ensure it is stored in environment variables not in code',
    SECRET_DB_PASSWORD: 'Change the database password, use a secrets manager or .env file with restricted permissions',
    SECRET_HARDCODED_PASSWORD: 'Remove the password from code, use environment variables or a secrets manager',
    SECRET_HARDCODED_TOKEN: 'Remove the token from code, use environment variables or a secrets manager',
    UNSAFE_EVAL: 'Replace eval() with safer alternatives like JSON.parse() or Function constructor wrappers',
    OS_CAPABILITY: 'Audit why child_process is needed, consider using higher-level APIs that don\'t spawn processes',
    NETWORK_ACTIVITY: 'Verify the destination is expected, use HTTPS only, pin certificates if possible',
    ENV_ACCESS: 'Review if all env var accesses are necessary, sanitize output to avoid leaking secrets',
    POTENTIAL_SECRET: 'Review the base64-decoded content, ensure it is not a secret being decoded for exfiltration',
    DOM_INJECTION: 'Use textContent instead of innerHTML, or sanitize input with DOMPurify',
    TYPOSQUAT_DEPENDENCY: 'Verify the package name is correct, use scoped packages (@scope/name) when possible',
    PHANTOM_DEPENDENCY: 'Remove unused dependencies from package.json, or install if actually needed',
  };
  return remediations[type] || 'Review the finding manually and apply appropriate security controls';
}
